# CHAPTER 4

# 1 - ARANGE METHOD 

In [1]:
import numpy as np
a = np.arange(1,4)
print(a)
print(a.shape)
a.dtype

[1 2 3]
(3,)


dtype('int32')

# 2 - EMPTY METHOD

In [2]:
from numpy import empty 
a = empty ([3,3])
a

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.37543423e-321],
       [8.90060779e-307, 3.82264778e-297, 3.21220882e-090]])

In [3]:
print(a.shape)
print(a.dtype)
print(a.ndim)

(3, 3)
float64
2


In [4]:
import numpy as np 
a =  np.empty ((3,3))
a

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.37543423e-321],
       [8.90060779e-307, 3.82264778e-297, 3.21220882e-090]])

# 3 - ZEROES METHOD

In [5]:
b =np.zeros([3,5], dtype=int)
b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# 4 - ONES METHOD

In [6]:
c = np.ones((5))
c

array([1., 1., 1., 1., 1.])

In [7]:
c = np.ones([3,5], dtype=int)
c

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# TASK # 1 

In [8]:
# WRITE A MATRIX OF 5 COLUMN AND 9 RAWS HAVE A SAME NUMBER 125

In [9]:
d = np.zeros((9,5) , dtype=int) +125
d

array([[125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125]])

# ANOTHER METHOD

In [10]:
import numpy as np
d = np.zeros((9,5) , dtype=int)
print(d)
e = np.full_like(d,125)
e

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


array([[125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125],
       [125, 125, 125, 125, 125]])

#  COMBINING ARRAYS

# Vertical stack

In [11]:
from numpy import array
from numpy import vstack
a1 = array ([1,2,3])
a2 = array ([4,5,6])
a3 = vstack([a1,a2])
print(a3)
print(a3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [12]:
import numpy as np
a1 = np.array ([1,2,3])
a2 = np.array ([4,5,6])
a3 = np.vstack([a1 ,a2])
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a1 = array ([1,2,3])
a2 = array ([4,5,6])
a3 = np.concatenate([a1,a2] ,axis=0)
a3

array([1, 2, 3, 4, 5, 6])

# Horizontal stack

In [14]:
from numpy import array
from numpy import hstack
a1 = array ([1,
             2,
             3])
a2 = array ([4,
             5,
             6])
a3 = hstack([a1,a2])
print(a3)
print(a3.shape)

[1 2 3 4 5 6]
(6,)


In [15]:
import numpy as np
a1 = np.array ([1,
                2,
                3])
a2 = np.array ([4,
                5,
                6])
a3 = np.vstack([a1 ,a2])
a3


array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a3.shape

(2, 3)

# TASK 

In [17]:
# 1- COMBINE TWO MATRIX OF GREATER THAN 3 RAWS AND COLUMN IN VERTICAL

In [18]:
a1 = np.array([[1 , 2 , 3 , 4],
             [1 , 2 , 3 , 4],
             [1 , 2 , 3 , 4],
             [1 ,  2 , 3 , 4]])
a2 = np.array([[4 , 5 , 6 , 7],
             [4 , 5 , 6 , 7],
             [4 , 5 , 6 , 7],
             [4 , 5 , 6 , 7]])
a3 = np.vstack([a1,a2])
a3

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [4, 5, 6, 7],
       [4, 5, 6, 7],
       [4, 5, 6, 7],
       [4, 5, 6, 7]])

In [19]:
a3.shape

(8, 4)

In [20]:
# 2- COMBINE TWO MATRIX OF GREATER THAN 3 RAWS AND COLUMN IN HORIZONTAL

In [21]:
a1 = np.array([[1 , 2 , 3 , 4],
             [1 , 2 , 3 , 4],
             [1 , 2 , 3 , 4],
             [1 ,  2 , 3 , 4]])
a2 = np.array([[4 , 5 , 6 , 7],
             [4 , 5 , 6 , 7],
             [4 , 5 , 6 , 7],
             [4 , 5 , 6 , 7]])
a3 = np.hstack([a1,a2])
a3

array([[1, 2, 3, 4, 4, 5, 6, 7],
       [1, 2, 3, 4, 4, 5, 6, 7],
       [1, 2, 3, 4, 4, 5, 6, 7],
       [1, 2, 3, 4, 4, 5, 6, 7]])

In [22]:
a3.shape

(4, 8)

# SLICING

# one dimension

In [23]:
from numpy import array 
data = ([11, 22 ,33 ,44 ,55])
data[4]

55

In [24]:
data[5]

IndexError: list index out of range

In [25]:
data[0]

11

In [26]:
data[-4]

22

In [27]:
data[-5]

11

In [28]:
from numpy import array 
data = ([11, 22 ,33 ,44 ,55])
data[-2:]

[44, 55]

In [29]:
from numpy import array 
data = ([11, 22 ,33 ,44 ,55])
data[-2::-1]

[44, 33, 22, 11]

In [30]:
from numpy import array 
data = ([11, 22 ,33 ,44 ,55])
data[0:3]

[11, 22, 33]

# two dimension

In [31]:
from numpy import array 
data = array([[11,22],
         [33,44],
         [55,66]])
print(data[0,0])

11


In [32]:
from numpy import array 
data =array ([[11,22],
         [33,44],
         [55,66]])
data.shape[0]

3

In [33]:
data.shape[1]

2

# three dimension

In [34]:
data = array([[11,22,33],
         [44,55,66],
         [77,88,99]])

x , y = data[: ,:-1] ,data[:, -1]
print(x)
y

[[11 22]
 [44 55]
 [77 88]]


array([33, 66, 99])

In [35]:
# TRAIN AND TEST DATA (IMPORTANT)

In [36]:
data = array([[11,22,33],
         [44,55,66],
         [77,88,99]])
split = 3
train,test = data[:split,:] , data[split:,:]
print(train)
test

[[11 22 33]
 [44 55 66]
 [77 88 99]]


array([], shape=(0, 3), dtype=int32)

In [37]:
data = array([[11,22,33],
         [44,55,66],
         [77,88,99]])
split = 2
train,test = data[:split,:] , data[split:,:]
print(train)
test

[[11 22 33]
 [44 55 66]]


array([[77, 88, 99]])

In [38]:
data = array([[11,22,33],
         [44,55,66],
         [77,88,99]])
split = 1
train,test = data[:split,:] , data[split:,:]
print(train)
test

[[11 22 33]]


array([[44, 55, 66],
       [77, 88, 99]])

In [39]:
data = array([[11,22,33],
         [44,55,66],
         [77,88,99]])
split = 0
train,test = data[:split,:] , data[split:,:]
print(train)
test

[]


array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

# 1d to 2d reshape

In [40]:
from numpy import array
data = array([11,22,33,44,55])
print(data.shape)
data = data.reshape((data.shape[0], 1))
data.shape

(5,)


(5, 1)

In [41]:
from numpy import array
data = array([11,22,33,44,55])
print(data)
print(data.shape)
data = data.reshape((data.shape[0], 1))
print(data)
data.shape

[11 22 33 44 55]
(5,)
[[11]
 [22]
 [33]
 [44]
 [55]]


(5, 1)

In [42]:
import numpy as np
a = np.arange(1,101).reshape(5,20)
print(a)
a.T.shape

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20]
 [ 21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
   39  40]
 [ 41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
   59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78
   79  80]
 [ 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98
   99 100]]


(20, 5)

## 2d to 3d reshape

In [43]:
a = np.arange(75).reshape((3,5,5))
print(a.shape)
a

(3, 5, 5)


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]]])

# TASK

In [44]:
# 1-TAKEOUT THE SECOND MATRIX FIRST RAW

In [45]:
a[2,0,0:]

array([50, 51, 52, 53, 54])

In [46]:
# 2- TAKE OUT 2ND MATRIX

In [47]:
a[2,0:,0:]

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [48]:
# EXTRA PRACTICE

In [49]:
a[1,0,0:]

array([25, 26, 27, 28, 29])

In [50]:
# 3-TAKE OUT 26 ,27 ,28 ENTIRE COLUMN

In [51]:
a[1,0:6,1:4]

array([[26, 27, 28],
       [31, 32, 33],
       [36, 37, 38],
       [41, 42, 43],
       [46, 47, 48]])

In [52]:
# OR
a[1,:,1:4]

array([[26, 27, 28],
       [31, 32, 33],
       [36, 37, 38],
       [41, 42, 43],
       [46, 47, 48]])

In [53]:
# 4- TAKE OUT THE ALTERNATE RAW OF EVERY MATRIX IN REVERSE ORDER

In [54]:
a[:,::2,::-1]

array([[[ 4,  3,  2,  1,  0],
        [14, 13, 12, 11, 10],
        [24, 23, 22, 21, 20]],

       [[29, 28, 27, 26, 25],
        [39, 38, 37, 36, 35],
        [49, 48, 47, 46, 45]],

       [[54, 53, 52, 51, 50],
        [64, 63, 62, 61, 60],
        [74, 73, 72, 71, 70]]])