In [1]:
import numpy as np

In [2]:
my_arr=np.arange(10)
my_arr
%time my_arr

Wall time: 0 ns


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
my_list=list(range(10))
my_list
%time my_list

Wall time: 0 ns


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
%time for _ in range(10): my_arr1= my_arr*2

Wall time: 0 ns


In [5]:
%time for _ in range(10): my_list2 = [x *2 for x in my_list]

Wall time: 0 ns


In [6]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [7]:
data = np.array(data2)

In [8]:
data

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
data.dtype

dtype('int32')

In [10]:
data.shape

(2, 4)

In [11]:
data = np.array(data2 , dtype = float)
data

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [12]:
data.shape

(2, 4)

In [13]:
data.astype(int)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
data 

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [15]:
data2 = [[1, 2, 3, 4],
         [5, 6, 7, 8]]

In [16]:
data1 = np.array(data2)
data1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
data1.ndim

2

In [18]:
data.ndim

2

In [19]:
data1.shape

(2, 4)

In [20]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
np.ones((1,6))

array([[1., 1., 1., 1., 1., 1.]])

In [22]:
e =3 * np.ones((2,4))
e

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [23]:
e.astype(int)

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

In [24]:
np.full_like(e , 6)

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [25]:
e > data1

array([[ True,  True, False, False],
       [False, False, False, False]])

In [26]:
e < data1

array([[False, False, False,  True],
       [ True,  True,  True,  True]])

### INDEXING

In [27]:
 w = np.arange(56).reshape(2,4,7)

In [28]:
w

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27]],

       [[28, 29, 30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55]]])

In [29]:
 arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [30]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
copy_array= arr3d[0].copy()


In [32]:
copy_array

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
copy_array[:] = 12

In [34]:
copy_array

array([[12, 12, 12],
       [12, 12, 12]])

In [35]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
copy = arr3d[:].copy()

In [37]:
copy[0] = 1

In [38]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
copy

array([[[ 1,  1,  1],
        [ 1,  1,  1]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
copy[0]

array([[1, 1, 1],
       [1, 1, 1]])

In [42]:
w[1,:2,:]

array([[28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41]])

In [43]:
w[:,:2,:]

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13]],

       [[28, 29, 30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39, 40, 41]]])

In [44]:
r  = np.arange(100).reshape(5,5,4)

In [45]:
r

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

In [46]:
r[[2,3,4,1],[3,2,1,0] , :]

array([[52, 53, 54, 55],
       [68, 69, 70, 71],
       [84, 85, 86, 87],
       [20, 21, 22, 23]])

In [47]:
 narray = np.empty(50).reshape(5,10)

In [48]:
warray = narray.astype(int)

In [49]:
for i in range(5):
    warray[i] = i+1

In [50]:
narray

array([[             nan,  9.88131292e-324,  3.00391913e-321,
         1.97626258e-323,  5.73116149e-321,  1.97626258e-323,
         4.98018171e-321,  2.03060980e-321,  5.03946959e-321,
         2.03060980e-321],
       [ 5.13828272e-321,  9.25190165e-312,  5.21733322e-321,
        -3.80261646e-311,  5.73116149e-321,  2.03060980e-321,
         5.75092412e-321,  2.03060980e-321,  3.00391913e-321,
         2.03060980e-321],
       [ 5.77068674e-321,  2.03060980e-321,  5.79044937e-321,
         9.25190165e-312,  3.00391913e-321,  1.97626258e-323,
         5.73116149e-321,  1.97626258e-323,  5.73116149e-321,
         9.25190165e-312],
       [ 5.75092412e-321,  2.03060980e-321,  3.00391913e-321,
         2.03060980e-321,  5.77068674e-321,  9.25190165e-312,
         5.79044937e-321,  2.03060980e-321,  3.00391913e-321,
         1.97626258e-323],
       [ 5.77068674e-321,  9.25190165e-312,  5.73116149e-321,
         1.97626258e-323,  0.00000000e+000,  0.00000000e+000,
         9.26343896e-312

# boolean indexing

In [51]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [52]:
data = np.random.randn(7, 4)


In [53]:
data[names == "Joe"]

array([[ 0.60237776,  0.01342156, -0.42598023,  0.87991705],
       [-0.5788361 , -1.43880434,  0.75912522,  0.05131228],
       [ 1.0176133 , -0.03719191,  0.9216235 , -0.9763224 ]])

In [54]:
data[~(names == "Joe")]

array([[ 1.43029743, -1.01369146, -0.14770858,  1.34146862],
       [ 0.57288735,  1.44404297, -0.18484796,  0.28830428],
       [ 0.12220766,  0.01746612,  0.902837  , -0.13168539],
       [-0.69114687,  0.31446315, -0.12184367, -1.09176356]])

In [55]:
data[~(names == "Bob") , :3]

array([[ 0.60237776,  0.01342156, -0.42598023],
       [ 0.57288735,  1.44404297, -0.18484796],
       [-0.69114687,  0.31446315, -0.12184367],
       [-0.5788361 , -1.43880434,  0.75912522],
       [ 1.0176133 , -0.03719191,  0.9216235 ]])