# BROADCASTING

In [1]:
# choti value map with greater value 

# airthmetic

In [2]:
a = [1 , 2, 3]
b = [1 , 2, 3]
c = a + b
c

[1, 2, 3, 1, 2, 3]

In [3]:
c = [1+1 , 2+2 , 3+3]
c

[2, 4, 6]

In [4]:
# RULES OF BROADCASTING:
# 1- JISKO BROADCASTING KRWANA HY USK LENGH KAM HO G ...
# EXAMPLE#
from numpy import array
a = array([1 , 2 ,3])
b = 2
c = a + b
c
# 2 value broadcast over array a..

array([3, 4, 5])

In [5]:
# scaler and two dimension .
a = array([[2, 3,4],
          [2 , 3,4]])
b = 2
c = a+b
c

array([[4, 5, 6],
       [4, 5, 6]])

In [6]:
# 2- (bara) no column of greater one array= (chota)no of elements on second array
# two dimension ky column = one dimension elements
# example
a = array([[2, 3,4],
          [2 , 3,4]])
b = array([1 , 2 ,3])
c = a+ b 
c

array([[3, 5, 7],
       [3, 5, 7]])

In [7]:
a = array([[2, 3,4 , 5],
          [2 , 3,4 , 5]])
b = array([1 , 2 ])
c = a+ b 
c

ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

In [10]:
a = array([[2, 3, 4 , 5],
          [2, 3, 4 , 5]])
b = array([[1 , 2 , 3 ,4 ],
           [1 , 2, 3 ,4]])
c = a+ b 
c

array([[3, 5, 7, 9],
       [3, 5, 7, 9]])

# Limitation of broadcasting

# test

In [11]:
import numpy as np 
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
a.ndim

2

In [13]:
a.dtype

dtype('int32')

In [14]:
a.size

15

In [15]:
a.itemsize

4

In [16]:
a.data

In [20]:
#total bit
b = a.itemsize * a.size
b

32

In [17]:
a = np.array([2,3,4])
a.dtype

dtype('int32')

In [18]:
a = np.array([2,3,4.5 , 6.5])
a.dtype

dtype('float64')

In [21]:
# array new array form krna ..
# as array form array ko chnage krta hy

In [22]:
b = np.array([(1,2,3),(4,5,6)])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
c = np.array([[1,2,3],[3,4,5]],dtype=complex)
c

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [3.+0.j, 4.+0.j, 5.+0.j]])

In [24]:
# sign : define sign
# unsign : not define sign by default it is postive
b = np.array([(-1,2,3),(4,5,6)])
b

array([[-1,  2,  3],
       [ 4,  5,  6]])

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((3 ,4 ),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [30]:
#task
a =np.zeros((3, 25,25),dtype=int) +25
a

array([[[25, 25, 25, ..., 25, 25, 25],
        [25, 25, 25, ..., 25, 25, 25],
        [25, 25, 25, ..., 25, 25, 25],
        ...,
        [25, 25, 25, ..., 25, 25, 25],
        [25, 25, 25, ..., 25, 25, 25],
        [25, 25, 25, ..., 25, 25, 25]],

       [[25, 25, 25, ..., 25, 25, 25],
        [25, 25, 25, ..., 25, 25, 25],
        [25, 25, 25, ..., 25, 25, 25],
        ...,
        [25, 25, 25, ..., 25, 25, 25],
        [25, 25, 25, ..., 25, 25, 25],
        [25, 25, 25, ..., 25, 25, 25]],

       [[25, 25, 25, ..., 25, 25, 25],
        [25, 25, 25, ..., 25, 25, 25],
        [25, 25, 25, ..., 25, 25, 25],
        ...,
        [25, 25, 25, ..., 25, 25, 25],
        [25, 25, 25, ..., 25, 25, 25],
        [25, 25, 25, ..., 25, 25, 25]]])

In [31]:
np.arange (10 , 30 ,5)

array([10, 15, 20, 25])

In [32]:
np.arange( 0, 2 ,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [1]:
np.set_printoption(threshold.np.nan)

NameError: name 'np' is not defined

In [42]:
# task
c = np.arange(7500).reshape(3,50,50)
c

array([[[   0,    1,    2, ...,   47,   48,   49],
        [  50,   51,   52, ...,   97,   98,   99],
        [ 100,  101,  102, ...,  147,  148,  149],
        ...,
        [2350, 2351, 2352, ..., 2397, 2398, 2399],
        [2400, 2401, 2402, ..., 2447, 2448, 2449],
        [2450, 2451, 2452, ..., 2497, 2498, 2499]],

       [[2500, 2501, 2502, ..., 2547, 2548, 2549],
        [2550, 2551, 2552, ..., 2597, 2598, 2599],
        [2600, 2601, 2602, ..., 2647, 2648, 2649],
        ...,
        [4850, 4851, 4852, ..., 4897, 4898, 4899],
        [4900, 4901, 4902, ..., 4947, 4948, 4949],
        [4950, 4951, 4952, ..., 4997, 4998, 4999]],

       [[5000, 5001, 5002, ..., 5047, 5048, 5049],
        [5050, 5051, 5052, ..., 5097, 5098, 5099],
        [5100, 5101, 5102, ..., 5147, 5148, 5149],
        ...,
        [7350, 7351, 7352, ..., 7397, 7398, 7399],
        [7400, 7401, 7402, ..., 7447, 7448, 7449],
        [7450, 7451, 7452, ..., 7497, 7498, 7499]]])

In [53]:
c[(c % 3 ==0) & (c% 5==0) & (c % 7 ==0)]

array([   0,  105,  210,  315,  420,  525,  630,  735,  840,  945, 1050,
       1155, 1260, 1365, 1470, 1575, 1680, 1785, 1890, 1995, 2100, 2205,
       2310, 2415, 2520, 2625, 2730, 2835, 2940, 3045, 3150, 3255, 3360,
       3465, 3570, 3675, 3780, 3885, 3990, 4095, 4200, 4305, 4410, 4515,
       4620, 4725, 4830, 4935, 5040, 5145, 5250, 5355, 5460, 5565, 5670,
       5775, 5880, 5985, 6090, 6195, 6300, 6405, 6510, 6615, 6720, 6825,
       6930, 7035, 7140, 7245, 7350, 7455])

In [55]:
b =np.arange(5*10*10).reshape(5,10,10)
b

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [75]:
b[[4,0,3,2,1]]

array([[[400, 401, 402, 403, 404, 405, 406, 407, 408, 409],
        [410, 411, 412, 413, 414, 415, 416, 417, 418, 419],
        [420, 421, 422, 423, 424, 425, 426, 427, 428, 429],
        [430, 431, 432, 433, 434, 435, 436, 437, 438, 439],
        [440, 441, 442, 443, 444, 445, 446, 447, 448, 449],
        [450, 451, 452, 453, 454, 455, 456, 457, 458, 459],
        [460, 461, 462, 463, 464, 465, 466, 467, 468, 469],
        [470, 471, 472, 473, 474, 475, 476, 477, 478, 479],
        [480, 481, 482, 483, 484, 485, 486, 487, 488, 489],
        [490, 491, 492, 493, 494, 495, 496, 497, 498, 499]],

       [[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,

In [77]:
e =b[[4,0,3,2,1],::2,::-1]
e

array([[[409, 408, 407, 406, 405, 404, 403, 402, 401, 400],
        [429, 428, 427, 426, 425, 424, 423, 422, 421, 420],
        [449, 448, 447, 446, 445, 444, 443, 442, 441, 440],
        [469, 468, 467, 466, 465, 464, 463, 462, 461, 460],
        [489, 488, 487, 486, 485, 484, 483, 482, 481, 480]],

       [[  9,   8,   7,   6,   5,   4,   3,   2,   1,   0],
        [ 29,  28,  27,  26,  25,  24,  23,  22,  21,  20],
        [ 49,  48,  47,  46,  45,  44,  43,  42,  41,  40],
        [ 69,  68,  67,  66,  65,  64,  63,  62,  61,  60],
        [ 89,  88,  87,  86,  85,  84,  83,  82,  81,  80]],

       [[309, 308, 307, 306, 305, 304, 303, 302, 301, 300],
        [329, 328, 327, 326, 325, 324, 323, 322, 321, 320],
        [349, 348, 347, 346, 345, 344, 343, 342, 341, 340],
        [369, 368, 367, 366, 365, 364, 363, 362, 361, 360],
        [389, 388, 387, 386, 385, 384, 383, 382, 381, 380]],

       [[209, 208, 207, 206, 205, 204, 203, 202, 201, 200],
        [229, 228, 227, 226, 225, 

In [78]:
e[[-1,0]]

array([[[109, 108, 107, 106, 105, 104, 103, 102, 101, 100],
        [129, 128, 127, 126, 125, 124, 123, 122, 121, 120],
        [149, 148, 147, 146, 145, 144, 143, 142, 141, 140],
        [169, 168, 167, 166, 165, 164, 163, 162, 161, 160],
        [189, 188, 187, 186, 185, 184, 183, 182, 181, 180]],

       [[409, 408, 407, 406, 405, 404, 403, 402, 401, 400],
        [429, 428, 427, 426, 425, 424, 423, 422, 421, 420],
        [449, 448, 447, 446, 445, 444, 443, 442, 441, 440],
        [469, 468, 467, 466, 465, 464, 463, 462, 461, 460],
        [489, 488, 487, 486, 485, 484, 483, 482, 481, 480]]])