In [1]:
import numpy as np

In [2]:
a = np.arange(100).reshape(5,4,5)

In [3]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [4]:
a.T

array([[[ 0, 20, 40, 60, 80],
        [ 5, 25, 45, 65, 85],
        [10, 30, 50, 70, 90],
        [15, 35, 55, 75, 95]],

       [[ 1, 21, 41, 61, 81],
        [ 6, 26, 46, 66, 86],
        [11, 31, 51, 71, 91],
        [16, 36, 56, 76, 96]],

       [[ 2, 22, 42, 62, 82],
        [ 7, 27, 47, 67, 87],
        [12, 32, 52, 72, 92],
        [17, 37, 57, 77, 97]],

       [[ 3, 23, 43, 63, 83],
        [ 8, 28, 48, 68, 88],
        [13, 33, 53, 73, 93],
        [18, 38, 58, 78, 98]],

       [[ 4, 24, 44, 64, 84],
        [ 9, 29, 49, 69, 89],
        [14, 34, 54, 74, 94],
        [19, 39, 59, 79, 99]]])

In [5]:
b = np.arange(10).reshape(2,5)

In [6]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
b.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [8]:
np.dot(b,b.T)

array([[ 30,  80],
       [ 80, 255]])

In [9]:
np.dot(a,a.T)

ValueError: shapes (5,4,5) and (5,4,5) not aligned: 5 (dim 2) != 4 (dim 1)

In [10]:
b.transpose((1,0))

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [11]:
a.transpose((1,0,2))

array([[[ 0,  1,  2,  3,  4],
        [20, 21, 22, 23, 24],
        [40, 41, 42, 43, 44],
        [60, 61, 62, 63, 64],
        [80, 81, 82, 83, 84]],

       [[ 5,  6,  7,  8,  9],
        [25, 26, 27, 28, 29],
        [45, 46, 47, 48, 49],
        [65, 66, 67, 68, 69],
        [85, 86, 87, 88, 89]],

       [[10, 11, 12, 13, 14],
        [30, 31, 32, 33, 34],
        [50, 51, 52, 53, 54],
        [70, 71, 72, 73, 74],
        [90, 91, 92, 93, 94]],

       [[15, 16, 17, 18, 19],
        [35, 36, 37, 38, 39],
        [55, 56, 57, 58, 59],
        [75, 76, 77, 78, 79],
        [95, 96, 97, 98, 99]]])

In [12]:
b.swapaxes(1,0)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [13]:
b.swapaxes(0,1)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [14]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
a.swapaxes(2,1)

array([[[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]],

       [[20, 25, 30, 35],
        [21, 26, 31, 36],
        [22, 27, 32, 37],
        [23, 28, 33, 38],
        [24, 29, 34, 39]],

       [[40, 45, 50, 55],
        [41, 46, 51, 56],
        [42, 47, 52, 57],
        [43, 48, 53, 58],
        [44, 49, 54, 59]],

       [[60, 65, 70, 75],
        [61, 66, 71, 76],
        [62, 67, 72, 77],
        [63, 68, 73, 78],
        [64, 69, 74, 79]],

       [[80, 85, 90, 95],
        [81, 86, 91, 96],
        [82, 87, 92, 97],
        [83, 88, 93, 98],
        [84, 89, 94, 99]]])

In [16]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [17]:
a.swapaxes(1,2)

array([[[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]],

       [[20, 25, 30, 35],
        [21, 26, 31, 36],
        [22, 27, 32, 37],
        [23, 28, 33, 38],
        [24, 29, 34, 39]],

       [[40, 45, 50, 55],
        [41, 46, 51, 56],
        [42, 47, 52, 57],
        [43, 48, 53, 58],
        [44, 49, 54, 59]],

       [[60, 65, 70, 75],
        [61, 66, 71, 76],
        [62, 67, 72, 77],
        [63, 68, 73, 78],
        [64, 69, 74, 79]],

       [[80, 85, 90, 95],
        [81, 86, 91, 96],
        [82, 87, 92, 97],
        [83, 88, 93, 98],
        [84, 89, 94, 99]]])