In [1]:
import numpy as np

In [8]:
a = np.arange(10).reshape(2,5)

In [9]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
b=np.arange(10).reshape(2,5)

In [13]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
c = np.sqrt(a)

In [16]:
c

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [18]:
np.maximum(a,b)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [21]:
d = np.square(a)
d

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]], dtype=int32)

In [23]:
np.maximum(b,d)

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [24]:
np.fmax(b,d)

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [25]:
np.floor_divide(b,d)

C:\Users\aqadi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


array([[0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [26]:
np.floor_divide(d,b)

C:\Users\aqadi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]], dtype=int32)

In [27]:
np.floor(a)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [28]:
np.floor(d)

array([[ 0.,  1.,  4.,  9., 16.],
       [25., 36., 49., 64., 81.]])

In [29]:
np.ceil(b)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])